In [47]:
import pandas as pd 

df = pd.read_csv('../data/quran.csv')

In [50]:
cols = list(df.columns)
cols[0] = 'chapter#'
cols[1] = 'verse#'
cols[2] = 'd_verse'
cols[3] = 'verse'
cols[9] = 'd_chapter'
cols[10] = 'chapter'
df.columns = cols

In [67]:
df.head()

,chapter#,verse#,d_verse,verse,22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9,0.25,1.1,١,1.2,d_chapter,chapter,1.3,0.1
0,1,1,بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,بسم الله الرحمٰن الرحيم,803dee27b5a9ddf866112eac2f8a34e5bd83ca08015ec4...,0.25,1,١,2,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
1,1,2,ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ,الحمد لله رب العٰلمين,ef2e84a7a99f9340845888a735cf6950853f9e1a13cff3...,0.25,1,١,3,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
2,1,3,ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,الرحمٰن الرحيم,fa43107ca02d890e5115053aed9835bfbefb79ffa68464...,0.25,1,١,4,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
3,1,4,مَٰلِكِ يَوۡمِ ٱلدِّينِ,مٰلك يوم الدين,4355fb3e57b0b8b4e47545d28d30b98359fea1a18e5bfc...,0.25,1,١,5,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
4,1,5,إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ,اياك نعبد واياك نستعين,8fc4ad4ff4e86be9abf8b5c66fd47a316b760844456c87...,0.25,1,١,6,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0

In [66]:
df[df['verse'].str.endswith("عليم")]

,chapter#,verse#,d_verse,verse,22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9,0.25,1.1,١,1.2,d_chapter,chapter,1.3,0.1
38,2,29,هُوَ ٱلَّذِي خَلَقَ لَكُم مَّا فِي ٱلۡأَرۡضِ ج...,هو الذي خلق لكم ما في الارض جميعا ثم استوىٰ ال...,1d46cfd791cef8e2baca0703534c88eae12043cf447fcf...,0.50,5,٥,39,سُورَةُ البَقَرَةِ,سورة البقرة,1,0
116,2,158,۞إِنَّ ٱلصَّفَا وَٱلۡمَرۡوَةَ مِن شَعَآئِرِ ٱ...,ان الصفا والمروة من شعائر الله فمن حج البيت او...,436916c0a8ca32649249db7134ea5ad9fed667138f0105...,2.50,24,٢٤,168,سُورَةُ البَقَرَةِ,سورة البقرة,2,0
130,2,115,وَلِلَّهِ ٱلۡمَشۡرِقُ وَٱلۡمَغۡرِبُۚ فَأَيۡنَم...,ولله المشرق والمغرب فاينما تولوا فثم وجه الله ...,74a1605daadb2f4d497857264d9a8d95c9485b4f8027c3...,1.75,18,١٨,125,سُورَةُ البَقَرَةِ,سورة البقرة,1,0
143,2,127,وَإِذۡ يَرۡفَعُ إِبۡرَٰهِـۧمُ ٱلۡقَوَاعِدَ مِن...,واذ يرفع ابرٰهم القواعد من البيت واسمٰعيل ربنا...,1637ddaf7949a7179c5e969734281760349c17723c1552...,2.00,20,٢٠,137,سُورَةُ البَقَرَةِ,سورة البقرة,1,0
154,2,137,فَإِنۡ ءَامَنُواْ بِمِثۡلِ مَآ ءَامَنتُم بِهِ...,فان ءامنوا بمثل ما ءامنتم به فقد اهتدوا وان تو...,708d4e413e14344db64487cd7c19317a433a1fa4be1aaf...,2.00,21,٢١,147,سُورَةُ البَقَرَةِ,سورة البقرة,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4843,51,28,فَأَوۡجَسَ مِنۡهُمۡ خِيفَةٗۖ قَالُواْ لَا تَخَ...,فاوجس منهم خيفة قالوا لا تخف وبشروه بغلٰم عليم,435608005b50ccb0c8013c262756db23ad881cefc8f367...,52.00,521,٥٢١,4803,سُورَةُ الذَّارِيَاتِ,سورة الذاريات,26,0
4845,51,30,قَالُواْ كَذَٰلِكِ قَالَ رَبُّكِۖ إِنَّهُۥ هُو...,قالوا كذٰلك قال ربك انه هو الحكيم العليم,3367ae9a1cbfd52ad49a9532c1ece20babfd8564178825...,52.00,521,٥٢١,4805,سُورَةُ الذَّارِيَاتِ,سورة الذاريات,26,0
5219,57,3,هُوَ ٱلۡأَوَّلُ وَٱلۡأٓخِرُ وَٱلظَّٰهِرُ وَٱلۡ...,هو الاول والاخر والظٰهر والباطن وهو بكل شيء عليم,0ac31b538bb8cfdfef218de50a782c104a07a0fda1a5ab...,53.75,537,٥٣٧,5190,سُورَةُ الحَدِيدِ,سورة الحديد,27,0
5257,58,7,أَلَمۡ تَرَ أَنَّ ٱللَّهَ يَعۡلَمُ مَا فِي ٱلس...,الم تر ان الله يعلم ما في السمٰوٰت وما في الار...,346e6075b845ad652c64f550daff6f02b573cb5ec6e50b...,54.25,543,٥٤٣,5225,سُورَةُ المُجَادلَةِ,سورة المجادلة,28,0
5375,64,11,مَآ أَصَابَ مِن مُّصِيبَةٍ إِلَّا بِإِذۡنِ ٱل...,ما اصاب من مصيبة الا باذن الله ومن يؤمن بالله ...,7513c593e5605194b34eba9f7b3be4b354b0010df81492...,55.50,557,٥٥٧,5336,سُورَةُ التَّغَابُنِ,سورة التغابن,28,0

In [78]:
df = df.sort_values(by=['chapter#','verse#']).reset_index(drop=True)

In [80]:
# Find rows where the PREVIOUS verse ends with the word
"""
mask = df['verse'].str.endswith("عليم", na=False)
next_rows_mask = mask.shift(1, fill_value=False)
df[next_rows_mask]
"""

# Find rows where the PREVIOUS verse ends with the word, and output both the previous verse and the current verse
for index, x in enumerate(df["verse"]):
    if pd.notna(x) and x.endswith("عليم"):
        print(x)
        if pd.notna(df["verse"][index+1]) :
            print(df["verse"][index+1] )

هو الذي خلق لكم ما في الارض جميعا ثم استوىٰ الى السماء فسوىٰهن سبع سمٰوٰت وهو بكل شيء عليم
واذ قال ربك للملٰئكة اني جاعل في الارض خليفة قالوا اتجعل فيها من يفسد فيها ويسفك الدماء ونحن نسبح بحمدك ونقدس لك قال اني اعلم ما لا تعلمون
ولله المشرق والمغرب فاينما تولوا فثم وجه الله ان الله وٰسع عليم
وقالوا اتخذ الله ولدا سبحٰنه بل له ما في السمٰوٰت والارض كل له قٰنتون
واذ يرفع ابرٰهم القواعد من البيت واسمٰعيل ربنا تقبل منا انك انت السميع العليم
ربنا واجعلنا مسلمين لك ومن ذريتنا امة مسلمة لك وارنا مناسكنا وتب علينا انك انت التواب الرحيم
فان ءامنوا بمثل ما ءامنتم به فقد اهتدوا وان تولوا فانما هم في شقاق فسيكفيكهم الله وهو السميع العليم
صبغة الله ومن احسن من الله صبغة ونحن له عٰبدون
ان الصفا والمروة من شعائر الله فمن حج البيت او اعتمر فلا جناح عليه ان يطوف بهما ومن تطوع خيرا فان الله شاكر عليم
ان الذين يكتمون ما انزلنا من البينٰت والهدىٰ من بعد ما بينٰه للناس في الكتٰب اولٰئك يلعنهم الله ويلعنهم اللٰعنون
فمن بدله بعد ما سمعه فانما اثمه على الذين يبدلونه ان الله سميع عليم
فمن خاف من موص جنفا او اثما فاصلح بينهم فلا اثم عليه ان الله غفور رحيم
يسلونك ماذا ينفقون قل ما انفقتم من خير فللوٰلدين والاقربين واليتٰمىٰ والمسٰكين وابن السبيل وما تفعلوا من خير فان الله به عليم
كتب عليكم القتال وهو كره لكم وعسىٰ ان تكرهوا شيا وهو خير لكم وعسىٰ ان تحبوا شيا وهو شر لكم والله يعلم وانتم لا تعلمون
ولا تجعلوا الله عرضة لايمٰنكم ان تبروا وتتقوا وتصلحوا بين الناس والله سميع عليم
لا يؤاخذكم الله باللغو في ايمٰنكم ولٰكن يؤاخذكم بما كسبت قلوبكم والله غفور حليم
وان عزموا الطلٰق فان الله سميع عليم
والمطلقٰت يتربصن بانفسهن ثلٰثة قروء ولا يحل لهن ان يكتمن ما خلق الله في ارحامهن ان كن يؤمن بالله واليوم الاخر وبعولتهن احق بردهن في ذٰلك ان ارادوا اصلٰحا ولهن مثل الذي عليهن بالمعروف وللرجال عليهن درجة والله عزيز حكيم
واذا طلقتم النساء فبلغن اجلهن فامسكوهن بمعروف او سرحوهن بمعروف ولا تمسكوهن ضرارا لتعتدوا ومن يفعل ذٰلك فقد ظلم نفسه ولا تتخذوا ءايٰت الله هزوا واذكروا نعمت الله عليكم وما انزل عليكم من الكتٰب والحكمة يعظكم به واتقوا الله واعلموا ان الله بكل شيء عليم
واذا طلقتم النساء فبلغن اجلهن فلا تعضلوهن ان ينكحن ازوٰجهن اذا ترٰضوا بينهم بالمعروف ذٰلك يوعظ به من كان منكم يؤمن بالله واليوم الاخر ذٰلكم ازكىٰ لكم واطهر والله يعلم وانتم لا تعلمون
وقٰتلوا في سبيل الله واعلموا ان الله سميع عليم
من ذا الذي يقرض الله قرضا حسنا فيضٰعفه له اضعافا كثيرة والله يقبض ويبصط واليه ترجعون
وقال لهم نبيهم ان الله قد بعث لكم طالوت ملكا قالوا انىٰ يكون له الملك علينا ونحن احق بالملك منه ولم يؤت سعة من المال قال ان الله اصطفىٰه عليكم وزاده بسطة في العلم والجسم والله يؤتي ملكه من يشاء والله وٰسع عليم
وقال لهم نبيهم ان ءاية ملكه ان ياتيكم التابوت فيه سكينة من ربكم وبقية مما ترك ءال موسىٰ وءال هٰرون تحمله الملٰئكة ان في ذٰلك لاية لكم ان كنتم مؤمنين
لا اكراه في الدين قد تبين الرشد من الغي فمن يكفر بالطٰغوت ويؤمن بالله فقد استمسك بالعروة الوثقىٰ لا انفصام لها والله سميع عليم
الله ولي الذين ءامنوا يخرجهم من الظلمٰت الى النور والذين كفروا اولياؤهم الطٰغوت يخرجونهم من النور الى الظلمٰت اولٰئك اصحٰب النار هم فيها خٰلدون
مثل الذين ينفقون اموٰلهم في سبيل الله كمثل حبة انبتت سبع سنابل في كل سنبلة مائة حبة والله يضٰعف لمن يشاء والله وٰسع عليم
الذين ينفقون اموٰلهم في سبيل الله ثم لا يتبعون ما انفقوا منا ولا اذى لهم اجرهم عند ربهم ولا خوف عليهم ولا هم يحزنون
الشيطٰن يعدكم الفقر ويامركم بالفحشاء والله يعدكم مغفرة منه وفضلا والله وٰسع عليم
يؤتي الحكمة من يشاء ومن يؤت الحكمة فقد اوتي خيرا كثيرا وما يذكر الا اولوا الالبٰب
للفقراء الذين احصروا في سبيل الله لا يستطيعون ضربا في الارض يحسبهم الجاهل اغنياء من التعفف تعرفهم بسيمٰهم لا يسلون الناس الحافا وما تنفقوا من خير فان الله به عليم
الذين ينفقون اموٰلهم باليل والنهار سرا وعلانية فلهم اجرهم عند ربهم ولا خوف عليهم ولا هم يحزنون
يٰايها الذين ءامنوا اذا تداينتم بدين الىٰ اجل مسمى فاكتبوه وليكتب بينكم كاتب بالعدل ولا ياب كاتب ان يكتب كما علمه الله فليكتب وليملل الذي عليه الحق وليتق الله ربه ولا يبخس منه شيا فان كان الذي عليه الحق سفيها او ضعيفا او لا يستطيع ان يمل هو فليملل وليه بالعدل واستشهدوا شهيدين من رجالكم فان لم يكونا رجلين فرجل وامراتان ممن ترضون من الشهداء ان تضل احدىٰهما فتذكر احدىٰهما الاخرىٰ ولا ياب الشهداء اذا ما دعوا ولا تسموا ان تكتبوه صغيرا او كبيرا الىٰ اجله ذٰلكم اقسط عند الله واقوم للشهٰدة وادنىٰ الا ترتابوا الا ان تكون تجٰرة حاضرة تديرونها بينكم فليس عليكم جناح الا تكتبوها واشهدوا اذا تبايعتم ولا يضار كاتب ولا شهيد وان تفعلوا فانه فسوق بكم واتقوا الله ويعلمكم الله والله بكل شيء عليم
وان كنتم علىٰ سفر ولم تجدوا كاتبا فرهٰن مقبوضة فان امن بعضكم بعضا فليؤد الذي اؤتمن امٰنته وليتق الله ربه ولا تكتموا الشهٰدة ومن يكتمها فانه ءاثم قلبه والله بما تعملون عليم
وان كنتم علىٰ سفر ولم تجدوا كاتبا فرهٰن مقبوضة فان امن بعضكم بعضا فليؤد الذي اؤتمن امٰنته وليتق الله ربه ولا تكتموا الشهٰدة ومن يكتمها فانه ءاثم قلبه والله بما تعملون عليم
لله ما في السمٰوٰت وما في الارض وان تبدوا ما في انفسكم او تخفوه يحاسبكم به الله فيغفر لمن يشاء ويعذب من يشاء والله علىٰ كل شيء قدير
ذرية بعضها من بعض والله سميع عليم
اذ قالت امرات عمرٰن رب اني نذرت لك ما في بطني محررا فتقبل مني انك انت السميع العليم
اذ قالت امرات عمرٰن رب اني نذرت لك ما في بطني محررا فتقبل مني انك انت السميع العليم
فلما وضعتها قالت رب اني وضعتها انثىٰ والله اعلم بما وضعت وليس الذكر كالانثىٰ واني سميتها مريم واني اعيذها بك وذريتها من الشيطٰن الرجيم
ولا تؤمنوا الا لمن تبع دينكم قل ان الهدىٰ هدى الله ان يؤتىٰ احد مثل ما اوتيتم او يحاجوكم عند ربكم قل ان الفضل بيد الله يؤتيه من يشاء والله وٰسع عليم
يختص برحمته من يشاء والله ذو الفضل العظيم
لن تنالوا البر حتىٰ تنفقوا مما تحبون وما تنفقوا من شيء فان الله به عليم
كل الطعام كان حلا لبني اسرٰءيل الا ما حرم اسرٰءيل علىٰ نفسه من قبل ان تنزل التورىٰة قل فاتوا بالتورىٰة فاتلوها ان كنتم صٰدقين
واذ غدوت من اهلك تبوئ المؤمنين مقٰعد للقتال والله سميع عليم
اذ همت طائفتان منكم ان تفشلا والله وليهما وعلى الله فليتوكل المؤمنون
يستفتونك قل الله يفتيكم في الكلٰلة ان امرؤا هلك ليس له ولد وله اخت فلها نصف ما ترك وهو يرثها ان لم يكن لها ولد فان كانتا اثنتين فلهما الثلثان مما ترك وان كانوا اخوة رجالا ونساء فللذكر مثل حظ الانثيين يبين الله لكم ان تضلوا والله بكل شيء عليم
سورة المائدة
يٰايها الذين ءامنوا من يرتد منكم عن دينه فسوف ياتي الله بقوم يحبهم ويحبونه اذلة على المؤمنين اعزة على الكٰفرين يجٰهدون في سبيل الله ولا يخافون لومة لائم ذٰلك فضل الله يؤتيه من يشاء والله وٰسع عليم
انما وليكم الله ورسوله والذين ءامنوا الذين يقيمون الصلوٰة ويؤتون الزكوٰة وهم رٰكعون
قل اتعبدون من دون الله ما لا يملك لكم ضرا ولا نفعا والله هو السميع العليم
قل يٰاهل الكتٰب لا تغلوا في دينكم غير الحق ولا تتبعوا اهواء قوم قد ضلوا من قبل واضلوا كثيرا وضلوا عن سواء السبيل
جعل الله الكعبة البيت الحرام قيٰما للناس والشهر الحرام والهدي والقلٰئد ذٰلك لتعلموا ان الله يعلم ما في السمٰوٰت وما في الارض وان الله بكل شيء عليم
اعلموا ان الله شديد العقاب وان الله غفور رحيم
وله ما سكن في اليل والنهار وهو السميع العليم
قل اغير الله اتخذ وليا فاطر السمٰوٰت والارض وهو يطعم ولا يطعم قل اني امرت ان اكون اول من اسلم ولا تكونن من المشركين
وتلك حجتنا ءاتينٰها ابرٰهيم علىٰ قومه نرفع درجٰت من نشاء ان ربك حكيم عليم
ووهبنا له اسحٰق ويعقوب كلا هدينا ونوحا هدينا من قبل ومن ذريته داود وسليمٰن وايوب ويوسف وموسىٰ وهٰرون وكذٰلك نجزي المحسنين
فالق الاصباح وجعل اليل سكنا والشمس والقمر حسبانا ذٰلك تقدير العزيز العليم
وهو الذي جعل لكم النجوم لتهتدوا بها في ظلمٰت البر والبحر قد فصلنا الايٰت لقوم يعلمون
بديع السمٰوٰت والارض انىٰ يكون له ولد ولم تكن له صٰحبة وخلق كل شيء وهو بكل شيء عليم
ذٰلكم الله ربكم لا الٰه الا هو خٰلق كل شيء فاعبدوه وهو علىٰ كل شيء وكيل
وتمت كلمت ربك صدقا وعدلا لا مبدل لكلمٰته وهو السميع العليم
وان تطع اكثر من في الارض يضلوك عن سبيل الله ان يتبعون الا الظن وان هم الا يخرصون
ويوم يحشرهم جميعا يٰمعشر الجن قد استكثرتم من الانس وقال اولياؤهم من الانس ربنا استمتع بعضنا ببعض وبلغنا اجلنا الذي اجلت لنا قال النار مثوىٰكم خٰلدين فيها الا ما شاء الله ان ربك حكيم عليم
وكذٰلك نولي بعض الظٰلمين بعضا بما كانوا يكسبون
وقالوا ما في بطون هٰذه الانعٰم خالصة لذكورنا ومحرم علىٰ ازوٰجنا وان يكن ميتة فهم فيه شركاء سيجزيهم وصفهم انه حكيم عليم
قد خسر الذين قتلوا اولٰدهم سفها بغير علم وحرموا ما رزقهم الله افتراء على الله قد ضلوا وما كانوا مهتدين
قال الملا من قوم فرعون ان هٰذا لسٰحر عليم
يريد ان يخرجكم من ارضكم فماذا تامرون
ياتوك بكل سٰحر عليم
وجاء السحرة فرعون قالوا ان لنا لاجرا ان كنا نحن الغٰلبين
واما ينزغنك من الشيطٰن نزغ فاستعذ بالله انه سميع عليم
ان الذين اتقوا اذا مسهم طٰئف من الشيطٰن تذكروا فاذا هم مبصرون
فلم تقتلوهم ولٰكن الله قتلهم وما رميت اذ رميت ولٰكن الله رمىٰ وليبلي المؤمنين منه بلاء حسنا ان الله سميع عليم
ذٰلكم وان الله موهن كيد الكٰفرين
اذ انتم بالعدوة الدنيا وهم بالعدوة القصوىٰ والركب اسفل منكم ولو تواعدتم لاختلفتم في الميعٰد ولٰكن ليقضي الله امرا كان مفعولا ليهلك من هلك عن بينة ويحيىٰ من حي عن بينة وان الله لسميع عليم
اذ يريكهم الله في منامك قليلا ولو ارىٰكهم كثيرا لفشلتم ولتنٰزعتم في الامر ولٰكن الله سلم انه عليم بذات الصدور
ذٰلك بان الله لم يك مغيرا نعمة انعمها علىٰ قوم حتىٰ يغيروا ما بانفسهم وان الله سميع عليم
كداب ءال فرعون والذين من قبلهم كذبوا بايٰت ربهم فاهلكنٰهم بذنوبهم واغرقنا ءال فرعون وكل كانوا ظٰلمين
وان جنحوا للسلم فاجنح لها وتوكل على الله انه هو السميع العليم
وان يريدوا ان يخدعوك فان حسبك الله هو الذي ايدك بنصره وبالمؤمنين
والذين ءامنوا من بعد وهاجروا وجٰهدوا معكم فاولٰئك منكم واولوا الارحام بعضهم اولىٰ ببعض في كتٰب الله ان الله بكل شيء عليم
سورة التوبة
ومن الاعراب من يتخذ ما ينفق مغرما ويتربص بكم الدوائر عليهم دائرة السوء والله سميع عليم
ومن الاعراب من يؤمن بالله واليوم الاخر ويتخذ ما ينفق قربٰت عند الله وصلوٰت الرسول الا انها قربة لهم سيدخلهم الله في رحمته ان الله غفور رحيم
خذ من اموٰلهم صدقة تطهرهم وتزكيهم بها وصل عليهم ان صلوٰتك سكن لهم والله سميع عليم
الم يعلموا ان الله هو يقبل التوبة عن عباده وياخذ الصدقٰت وان الله هو التواب الرحيم
وما كان الله ليضل قوما بعد اذ هدىٰهم حتىٰ يبين لهم ما يتقون ان الله بكل شيء عليم
ان الله له ملك السمٰوٰت والارض يحي ويميت وما لكم من دون الله من ولي ولا نصير
ولا يحزنك قولهم ان العزة لله جميعا هو السميع العليم
الا ان لله من في السمٰوٰت ومن في الارض وما يتبع الذين يدعون من دون الله شركاء ان يتبعون الا الظن وان هم الا يخرصون
وقال فرعون ائتوني بكل سٰحر عليم
فلما جاء السحرة قال لهم موسىٰ القوا ما انتم ملقون
فاستجاب له ربه فصرف عنه كيدهن انه هو السميع العليم
ثم بدا لهم من بعد ما راوا الايٰت ليسجننه حتىٰ حين
وقال الملك ائتوني به فلما جاءه الرسول قال ارجع الىٰ ربك فسله ما بال النسوة الٰتي قطعن ايديهن ان ربي بكيدهن عليم
قال ما خطبكن اذ رٰودتن يوسف عن نفسه قلن حٰش لله ما علمنا عليه من سوء قالت امرات العزيز الٰن حصحص الحق انا رٰودته عن نفسه وانه لمن الصٰدقين
قال اجعلني علىٰ خزائن الارض اني حفيظ عليم
وكذٰلك مكنا ليوسف في الارض يتبوا منها حيث يشاء نصيب برحمتنا من نشاء ولا نضيع اجر المحسنين
فبدا باوعيتهم قبل وعاء اخيه ثم استخرجها من وعاء اخيه كذٰلك كدنا ليوسف ما كان لياخذ اخاه في دين الملك الا ان يشاء الله نرفع درجٰت من نشاء وفوق كل ذي علم عليم
قالوا ان يسرق فقد سرق اخ له من قبل فاسرها يوسف في نفسه ولم يبدها لهم قال انتم شر مكانا والله اعلم بما تصفون
وان ربك هو يحشرهم انه حكيم عليم
ولقد خلقنا الانسٰن من صلصٰل من حما مسنون
قالوا لا توجل انا نبشرك بغلٰم عليم
قال ابشرتموني علىٰ ان مسني الكبر فبم تبشرون
ان ربك هو الخلٰق العليم
ولقد ءاتينٰك سبعا من المثاني والقرءان العظيم
قال ربي يعلم القول في السماء والارض وهو السميع العليم
بل قالوا اضغٰث احلٰم بل افترىٰه بل هو شاعر فلياتنا باية كما ارسل الاولون
يٰايها الرسل كلوا من الطيبٰت واعملوا صٰلحا اني بما تعملون عليم
وان هٰذه امتكم امة وٰحدة وانا ربكم فاتقون
يٰايها الذين ءامنوا لا تتبعوا خطوٰت الشيطٰن ومن يتبع خطوٰت الشيطٰن فانه يامر بالفحشاء والمنكر ولولا فضل الله عليكم ورحمته ما زكىٰ منكم من احد ابدا ولٰكن الله يزكي من يشاء والله سميع عليم
ولا ياتل اولوا الفضل منكم والسعة ان يؤتوا اولي القربىٰ والمسٰكين والمهٰجرين في سبيل الله وليعفوا وليصفحوا الا تحبون ان يغفر الله لكم والله غفور رحيم
فان لم تجدوا فيها احدا فلا تدخلوها حتىٰ يؤذن لكم وان قيل لكم ارجعوا فارجعوا هو ازكىٰ لكم والله بما تعملون عليم
ليس عليكم جناح ان تدخلوا بيوتا غير مسكونة فيها متٰع لكم والله يعلم ما تبدون وما تكتمون
وانكحوا الايٰمىٰ منكم والصٰلحين من عبادكم وامائكم ان يكونوا فقراء يغنهم الله من فضله والله وٰسع عليم
وليستعفف الذين لا يجدون نكاحا حتىٰ يغنيهم الله من فضله والذين يبتغون الكتٰب مما ملكت ايمٰنكم فكاتبوهم ان علمتم فيهم خيرا وءاتوهم من مال الله الذي ءاتىٰكم ولا تكرهوا فتيٰتكم على البغاء ان اردن تحصنا لتبتغوا عرض الحيوٰة الدنيا ومن يكرههن فان الله من بعد اكرٰههن غفور رحيم
الله نور السمٰوٰت والارض مثل نوره كمشكوٰة فيها مصباح المصباح في زجاجة الزجاجة كانها كوكب دري يوقد من شجرة مبٰركة زيتونة لا شرقية ولا غربية يكاد زيتها يضيء ولو لم تمسسه نار نور علىٰ نور يهدي الله لنوره من يشاء ويضرب الله الامثٰل للناس والله بكل شيء عليم
في بيوت اذن الله ان ترفع ويذكر فيها اسمه يسبح له فيها بالغدو والاصال
والقوٰعد من النساء الٰتي لا يرجون نكاحا فليس عليهن جناح ان يضعن ثيابهن غير متبرجٰت بزينة وان يستعففن خير لهن والله سميع عليم
ليس على الاعمىٰ حرج ولا على الاعرج حرج ولا على المريض حرج ولا علىٰ انفسكم ان تاكلوا من بيوتكم او بيوت ءابائكم او بيوت امهٰتكم او بيوت اخوٰنكم او بيوت اخوٰتكم او بيوت اعمٰمكم او بيوت عمٰتكم او بيوت اخوٰلكم او بيوت خٰلٰتكم او ما ملكتم مفاتحه او صديقكم ليس عليكم جناح ان تاكلوا جميعا او اشتاتا فاذا دخلتم بيوتا فسلموا علىٰ انفسكم تحية من عند الله مبٰركة طيبة كذٰلك يبين الله لكم الايٰت لعلكم تعقلون
الا ان لله ما في السمٰوٰت والارض قد يعلم ما انتم عليه ويوم يرجعون اليه فينبئهم بما عملوا والله بكل شيء عليم
سورة الفرقان
قال للملا حوله ان هٰذا لسٰحر عليم
يريد ان يخرجكم من ارضكم بسحره فماذا تامرون
ياتوك بكل سحار عليم
فجمع السحرة لميقٰت يوم معلوم
انه هو السميع العليم
هل انبئكم علىٰ من تنزل الشيٰطين
وانك لتلقى القرءان من لدن حكيم عليم
اذ قال موسىٰ لاهله اني ءانست نارا ساتيكم منها بخبر او ءاتيكم بشهاب قبس لعلكم تصطلون
ان ربك يقضي بينهم بحكمه وهو العزيز العليم
فتوكل على الله انك على الحق المبين
من كان يرجوا لقاء الله فان اجل الله لات وهو السميع العليم
ومن جٰهد فانما يجٰهد لنفسه ان الله لغني عن العٰلمين
وكاين من دابة لا تحمل رزقها الله يرزقها واياكم وهو السميع العليم
ولئن سالتهم من خلق السمٰوٰت والارض وسخر الشمس والقمر ليقولن الله فانىٰ يؤفكون
الله يبسط الرزق لمن يشاء من عباده ويقدر له ان الله بكل شيء عليم
ولئن سالتهم من نزل من السماء ماء فاحيا به الارض من بعد موتها ليقولن الله قل الحمد لله بل اكثرهم لا يعقلون
قل يجمع بيننا ربنا ثم يفتح بيننا بالحق وهو الفتاح العليم
قل اروني الذين الحقتم به شركاء كلا بل هو الله العزيز الحكيم
والشمس تجري لمستقر لها ذٰلك تقدير العزيز العليم
والقمر قدرنٰه منازل حتىٰ عاد كالعرجون القديم
قل يحييها الذي انشاها اول مرة وهو بكل خلق عليم
الذي جعل لكم من الشجر الاخضر نارا فاذا انتم منه توقدون
اوليس الذي خلق السمٰوٰت والارض بقٰدر علىٰ ان يخلق مثلهم بلىٰ وهو الخلٰق العليم
انما امره اذا اراد شيا ان يقول له كن فيكون
تنزيل الكتٰب من الله العزيز العليم
غافر الذنب وقابل التوب شديد العقاب ذي الطول لا الٰه الا هو اليه المصير
فقضىٰهن سبع سمٰوات في يومين واوحىٰ في كل سماء امرها وزينا السماء الدنيا بمصٰبيح وحفظا ذٰلك تقدير العزيز العليم
فان اعرضوا فقل انذرتكم صٰعقة مثل صٰعقة عاد وثمود
واما ينزغنك من الشيطٰن نزغ فاستعذ بالله انه هو السميع العليم
ومن ءايٰته اليل والنهار والشمس والقمر لا تسجدوا للشمس ولا للقمر واسجدوا لله الذي خلقهن ان كنتم اياه تعبدون
له مقاليد السمٰوٰت والارض يبسط الرزق لمن يشاء ويقدر انه بكل شيء عليم
شرع لكم من الدين ما وصىٰ به نوحا والذي اوحينا اليك وما وصينا به ابرٰهيم وموسىٰ وعيسىٰ ان اقيموا الدين ولا تتفرقوا فيه كبر على المشركين ما تدعوهم اليه الله يجتبي اليه من يشاء ويهدي اليه من ينيب
ولئن سالتهم من خلق السمٰوٰت والارض ليقولن خلقهن العزيز العليم
الذي جعل لكم الارض مهدا وجعل لكم فيها سبلا لعلكم تهتدون
وهو الذي في السماء الٰه وفي الارض الٰه وهو الحكيم العليم
وتبارك الذي له ملك السمٰوٰت والارض وما بينهما وعنده علم الساعة واليه ترجعون
رحمة من ربك انه هو السميع العليم
رب السمٰوٰت والارض وما بينهما ان كنتم موقنين
يٰايها الذين ءامنوا لا تقدموا بين يدي الله ورسوله واتقوا الله ان الله سميع عليم
يٰايها الذين ءامنوا لا ترفعوا اصوٰتكم فوق صوت النبي ولا تجهروا له بالقول كجهر بعضكم لبعض ان تحبط اعمٰلكم وانتم لا تشعرون
قل اتعلمون الله بدينكم والله يعلم ما في السمٰوٰت وما في الارض والله بكل شيء عليم
يمنون عليك ان اسلموا قل لا تمنوا علي اسلٰمكم بل الله يمن عليكم ان هدىٰكم للايمٰن ان كنتم صٰدقين
فاوجس منهم خيفة قالوا لا تخف وبشروه بغلٰم عليم
فاقبلت امراته في صرة فصكت وجهها وقالت عجوز عقيم
قالوا كذٰلك قال ربك انه هو الحكيم العليم
قال فما خطبكم ايها المرسلون
هو الاول والاخر والظٰهر والباطن وهو بكل شيء عليم
هو الذي خلق السمٰوٰت والارض في ستة ايام ثم استوىٰ على العرش يعلم ما يلج في الارض وما يخرج منها وما ينزل من السماء وما يعرج فيها وهو معكم اين ما كنتم والله بما تعملون بصير
الم تر ان الله يعلم ما في السمٰوٰت وما في الارض ما يكون من نجوىٰ ثلٰثة الا هو رابعهم ولا خمسة الا هو سادسهم ولا ادنىٰ من ذٰلك ولا اكثر الا هو معهم اين ما كانوا ثم ينبئهم بما عملوا يوم القيٰمة ان الله بكل شيء عليم
الم تر الى الذين نهوا عن النجوىٰ ثم يعودون لما نهوا عنه ويتنٰجون بالاثم والعدوٰن ومعصيت الرسول واذا جاءوك حيوك بما لم يحيك به الله ويقولون في انفسهم لولا يعذبنا الله بما نقول حسبهم جهنم يصلونها فبئس المصير
ما اصاب من مصيبة الا باذن الله ومن يؤمن بالله يهد قلبه والله بكل شيء عليم
واطيعوا الله واطيعوا الرسول فان توليتم فانما علىٰ رسولنا البلٰغ المبين

In [85]:


# Then display
df.head()

,chapter#,verse#,d_verse,verse,22b81fd12c136d4cf67a37de941908d83eaf8e97571c4983f9308d30d52ad8f9,0.25,1.1,١,1.2,d_chapter,chapter,1.3,0.1
0,1,1,بِسۡمِ ٱللَّهِ ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,بسم الله الرحمٰن الرحيم,803dee27b5a9ddf866112eac2f8a34e5bd83ca08015ec4acaaffeba25a378352,0.25,1,١,2,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
1,1,2,ٱلۡحَمۡدُ لِلَّهِ رَبِّ ٱلۡعَٰلَمِينَ,الحمد لله رب العٰلمين,ef2e84a7a99f9340845888a735cf6950853f9e1a13cff30f4c1e7648e56ee51b,0.25,1,١,3,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
2,1,3,ٱلرَّحۡمَٰنِ ٱلرَّحِيمِ,الرحمٰن الرحيم,fa43107ca02d890e5115053aed9835bfbefb79ffa6846491cf7dfc67c8fd8be7,0.25,1,١,4,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
3,1,4,مَٰلِكِ يَوۡمِ ٱلدِّينِ,مٰلك يوم الدين,4355fb3e57b0b8b4e47545d28d30b98359fea1a18e5bfc3dc948eeab653901e5,0.25,1,١,5,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0
4,1,5,إِيَّاكَ نَعۡبُدُ وَإِيَّاكَ نَسۡتَعِينُ,اياك نعبد واياك نستعين,8fc4ad4ff4e86be9abf8b5c66fd47a316b760844456c87ec85806ac3473471e9,0.25,1,١,6,سُورَةُ الفَاتِحَةِ,سورة الفاتحة,1,0